version: '3.3'

services:
  app:
    image: myspringbootcompose:latest
    build:
      context: .
    ports:
      - 8080:8080
    container_name: app
    networks:
      - backnet
      - frontnet
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=/run/secrets/postgresql_root_password
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.yaml
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - MANAGEMENT_SERVER_PORT=8081
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
    secrets:
      - postgresql_root_password
      
  db:
    image: 'postgres:13.1-alpine'
    ports:
      - 8082:5432
    networks:
      - backnet
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=/run/secrets/postgresql_root_password
      - POSTGRES_DB=testdb

secrets:
  postgresql_root_password:
    file: password.txt
    
networks:
  backnet:
  frontnet: